# Generated by Django 4.2.6 on 2023-10-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player1_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rock", "Rock"),
                            ("paper", "Paper"),
                            ("scissors", "Scissors"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "player2_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rock", "Rock"),
                            ("paper", "Paper"),
                            ("scissors", "Scissors"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for opponent"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player1_sessions",
                        to="base.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player2_sessions",
                        to="base.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winning_sessions",
                        to="base.player",
                    ),
                ),
            ],
        ),
    ]
